### ISSUE TITLE
panic when used with `lazy` and `futures_unordered`

### ISSUE THREAD

**Issue by cristicbz** [alexcrichton/tokio-process#9]
The code below panics inside `futures-rs` in the [`futures_unordered` code](https://github.com/alexcrichton/futures-rs/blob/master/src/stream/futures_unordered.rs#L62) with:

<details>
<summary>Backtrace</summary>

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:323
stack backtrace:
[snip]
  10:     0x5649bcc735f6 - <core::option::Option<T>>::unwrap::h642f7c068445ae4e
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libcore/macros.rs:21
  11:     0x5649bcc83ed6 - <futures::stream::futures_unordered::FuturesUnordered<F>>::poll_pending::{{closure}}::h954ecdfdfd323d03
                        at /home/ccc/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.7/src/stream/futures_unordered.rs:62
  12:     0x5649bcc83b14 - futures::task_impl::set::{{closure}}::h560830c9e059fd67
                        at /home/ccc/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.7/src/task_impl/mod.rs:50
  13:     0x5649bcc75547 - <std::thread::local::LocalKey<T>>::with::h3800e0f5fcfcea62
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/thread/local.rs:245
  14:     0x5649bcc810fc - futures::task_impl::set::h7e95b88a5f7141ce
                        at /home/ccc/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.7/src/task_impl/mod.rs:47
  15:     0x5649bcc840bd - futures::task_impl::with_unpark_event::{{closure}}::hfa7c126081c43a6f
                        at /home/ccc/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.7/src/task_impl/mod.rs:175
  16:     0x5649bcc8129f - futures::task_impl::with::ha915d1fae7cdc9bd
                        at /home/ccc/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.7/src/task_impl/mod.rs:59
  17:     0x5649bcc80f9d - futures::task_impl::with_unpark_event::hd5032afd15a5248c
                        at /home/ccc/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.7/src/task_impl/mod.rs:169
  18:     0x5649bcc7ffa6 - <futures::stream::futures_unordered::FuturesUnordered<F>>::poll_pending::h04ec315f6c45215f
                        at /home/ccc/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.7/src/stream/futures_unordered.rs:61
  19:     0x5649bcc70a91 - <futures::stream::futures_unordered::FuturesUnordered<F> as futures::stream::Stream>::poll::hc492960ef1e227c6
                        at /home/ccc/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.7/src/stream/futures_unordered.rs:91
  20:     0x5649bcc82ac7 - <futures::stream::for_each::ForEach<S, F> as futures::future::Future>::poll::h621a63904f71d2d2
                        at /home/ccc/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.7/src/stream/for_each.rs:33
  21:     0x5649bcc8398b - <futures::task_impl::Spawn<F>>::poll_future::{{closure}}::h804f006440964da5
                        at /home/ccc/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.7/src/task_impl/mod.rs:312
  22:     0x5649bcc839dd - <futures::task_impl::Spawn<T>>::enter::{{closure}}::hdd9776e9db4088f9
                        at /home/ccc/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.7/src/task_impl/mod.rs:399
  23:     0x5649bcc83cca - futures::task_impl::set::{{closure}}::h596080fa8a446473
                        at /home/ccc/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.7/src/task_impl/mod.rs:50
  24:     0x5649bcc75a4d - <std::thread::local::LocalKey<T>>::with::he2aabe090a2730e5
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/thread/local.rs:245
  25:     0x5649bcc81049 - futures::task_impl::set::h2d2ae3a053db8d54
                        at /home/ccc/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.7/src/task_impl/mod.rs:47
  26:     0x5649bcc750b7 - <futures::task_impl::Spawn<T>>::enter::hfc409b34a5f2b122
                        at /home/ccc/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.7/src/task_impl/mod.rs:399
  27:     0x5649bcc74f29 - <futures::task_impl::Spawn<F>>::poll_future::hfe47b0c45c42d612
                        at /home/ccc/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.7/src/task_impl/mod.rs:312
  28:     0x5649bcc838de - tokio_core::reactor::Core::run::{{closure}}::hfa76b621a98ff98e
                        at /home/ccc/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.2/src/reactor/mod.rs:218
  29:     0x5649bcc7431a - <scoped_tls::ScopedKey<T>>::set::h0280b1c7849c9f03
                        at /home/ccc/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.0/src/lib.rs:135
  30:     0x5649bcc70fcf - tokio_core::reactor::Core::run::h9d2a866c5ed43fc0
                        at /home/ccc/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.2/src/reactor/mod.rs:217
  31:     0x5649bcc8372a - futures_r::main::h765ab9f7cf9cc98b
                        at /home/ccc/e/futures-r/src/main.rs:22
[snip]
```

</details>

---
File `main.rs`:
```rust
extern crate futures;
extern crate tokio_core;
extern crate tokio_process;

use futures::{Future, Stream, BoxFuture};
use tokio_core::reactor::{Core, Handle};
use tokio_process::CommandExt;
use std::process::Command;
use std::io::Error as IoError;

fn command(handle: &Handle) -> BoxFuture<(), IoError> {
    let mut command = Command::new("echo");
    command.arg("hello");
    let future = command.output_async(handle);
    // Removing lazy gets rid of the panic.
    futures::lazy(|| future.map(|_| ())).boxed()
}

fn main() {
    let mut core = Core::new().expect("");
    let handle = core.handle();
    // A single call to `command` gets rid of the panic.
    let commands = vec![command(&handle), command(&handle)]; 
    core.run(futures::stream::futures_unordered(commands).for_each(|_| Ok(())))
        .expect("");
}
```

File `Cargo.toml`:
```toml
[package]
authors = ["Cristi Cobzarenco <cristi.cobzarenco@gmail.com>"]
name = "futures-r"
version = "0.1.0"

[dependencies]
futures = "0.1.7"
tokio-core = "0.1.2"
tokio-process = "0.1.1"
```

**Comment by alexcrichton** [comment]
Turns out this was a bug in futures!
